export class fetchAllDe {
  id?: number;
  app_no_ide?: string | null;
  app_no_de?: string | null;
  curef?: string | null;
  id_customer?: number;
  nama?: string | null;
  jenis_kelamin?: string | null;
  tanggal_lahir?: string | null;
  tempat_lahir?: string | null;
  status_perkawinan?: string | null;
  agama?: string | null;
  pendidikan?: string | null;
  kewarganegaraan?: string | null;
  nama_ibu_kandung?: string | null;
  npwp?: number;
  alamat_ktp?: string | null;
  provinsi?: string | null;
  kabkota?: string | null;
  kecamatan?: string | null;
  kelurahan?: string | null;
  kode_pos?: number;
  rt?: number;
  rw?: number;
  no_ktp?: number;
  tanggal_terbit_ktp?: string | null;
  tanggal_exp_ktp?: string | null;
  no_handphone?: number;
  nama_pasangan?: string | null;
  jenis_kelamin_pasangan?: string | null;
  tanggal_lahir_pasangan?: string | null;
  tempat_lahir_pasangan?: string | null;
  agama_pasangan?: string | null;
  pendidikan_pasangan?: string | null;
  kewarganegaraan_pasangan?: string | null;
  nama_ibu_kandung_pasangan?: string | null;
  npwp_pasangan?: number;
  alamat_ktp_pasangan?: string | null;
  provinsi_pasangan?: string | null;
  kabkota_pasangan?: string | null;
  kecamatan_pasangan?: string | null;
  kelurahan_pasangan?: string | null;
  kode_pos_pasangan?: number;
  rt_pasangan?: number;
  rw_pasangan?: number;
  no_ktp_pasangan?: number;
  tanggal_terbit_ktp_pasangan?: string | null;
  tanggal_exp_ktp_pasangan?: string | null;
  no_handphone_pasangan?: number;
  alamat_domisili?: string | null;
  provinsi_domisili?: string | null;
  kabkota_domisili?: string | null;
  kecamatan_domisili?: string | null;
  kelurahan_domisili?: string | null;
  kode_pos_domisili?: number;
  rt_domisili?: number;
  rw_domisili?: number;
  jumlah_anak?: number;
  status_rumah?: number;
  lama_menetap?: number;
  status_kendaraan?: number;
  tipe_kendaraan?: string | null;
  email?: string | null;
  no_telepon?: number;
  usia?: number;
  usia_pasangan?: number;
  kategori_pekerjaan?: string | null;
  status_ktp?: string | null;
  status_ktp_pasangan?: string | null;
  email_pasangan?: string | null;
  customer_created_date?: string | null;
  customer_updated_date?: string | null;
  kode_fasilitas?: string | null;
  program_pembiayaan?: string | null;
  produk_pembiayaan?: string | null;
  status_aplikasi_desc?: string | null;
  status_aplikasi?: string | null;
  status_alamat?: string | null;
  jangka_waktu?: number;
  nilai_pembiayaan?: number;
  kode_fasilitas_name?: string | null;
}
