export class listScoring {
  id?: number;
  produk?: string;
  joint_income?: number;
  parameter?: string;
  data_value?: string;
  min_value?: number;
  max_value?: number;
  score?: number;
  created_date?: string;
  created_by?: string;
  kode_program?: string;
  kode_fasilitas?: string;
  deskripsi_program?: string;
  updated_date?: string;
  updated_by?: string;
  parameter_type?: string;
  id_score?: string;
  fasilitas?: number;
  tipe_properti_deskripsi?: string;
  min?: number;
  max?: number;
  ftv?: number;
  dp?: number;
  score_ftv_less: number | string | undefined | null;
  score_ftv_equal: number | string | undefined | null;
  kode_produk?: string;
  nama_produk?: string;
  id_detail?: number;
  program?: string;
  id_ftv_dp_detail?: number;
}
