export class refAnalisaDataKantor {
  id?: number;
  app_no_de?: string;
  tanggal_verifikasi?: string;
  pemberi_keterangan?: string;
  hubungan_pemberi_keterangan?: string;
  verif_fax?: number;
  note_verif_fax?: string;
  verif_no_telepon?: number;
  note_verif_no_telepon?: string;
  verif_alamat_perusahaan?: number;
  note_verif_alamat_perusahaan?: string;
  verif_nama_perusahaan?: number;
  note_verif_nama_perusahaan?: string;
  verif_provinsi?: number;
  note_verif_provinsi?: string;
  verif_kabkota?: number;
  note_verif_kabkota?: string;
  verif_kecamatan?: number;
  note_verif_kecamatan?: string;
  verif_kelurahan?: number;
  note_verif_kelurahan?: string;
  verif_kode_pos?: number;
  note_verif_kode_pos?: string;
  verif_lama_bekerja?: number;
  note_verif_lama_bekerja?: string;
  verif_lama_beroperasi?: number;
  note_verif_lama_beroperasi?: string;
  verif_bidang_usaha?: number;
  note_verif_bidang_usaha?: string;
  verif_tipe_perusahaan?: number;
  note_verif_tipe_perusahaan?: string;
  verif_jenis_pekerjaan?: number;
  note_verif_jenis_pekerjaan?: string;
  verif_jumlah_karyawan?: number;
  note_verif_jumlah_karyawan?: string;
  verif_sektor_ekonomi?: number;
  note_verif_sektor_ekonomi?: string;
  verif_tipe_pekerjaan?: number;
  note_verif_tipe_pekerjaan?: string;
  verif_status_kepegawaian?: number;
  note_verif_status_kepegawaian?: string;
  verif_jabatan?: number;
  note_verif_jabatan?: string;
  verif_usia_pensiun?: number;
  note_verif_usia_pensiun?: string;
  divisi?: string;
  aspek_syariah?: number;
  created_date?: string;
  updated_date?: string;
  created_by?: string;
  updated_by?: string;
  waktu_verifikasi?: string;

  jumlah_pinjaman_kantor: string | number | null | undefined;
  komponen_gaji: string | number | null | undefined;
  pembayaran_gaji: string | number | null | undefined;
  tenor_pinjaman_kantor: string | number | null | undefined;
}
