export class getCallReportModel {
  alamat_tinggal: string | undefined;
  tanggal_lahir: string | undefined;
  status_kawin: string | undefined;
  pendidikan: string | undefined;
  kendaraan: string | undefined;
  status_agunan: string | undefined;
  catatan_status_agunan: string | undefined;
  dokumen_agunan: string | undefined;
  catatan_dokumen_agunan: string | undefined;
  posisi_dokumen: string | undefined;
  catatan_posisi_dokumen: string | undefined;
  tipe_pekerjaan: string | undefined;
  status_pekerjaan: string | undefined;
  lama_bekerja_tahun: number | null | undefined;
  lama_bekerja_bulan: number | null | undefined;
  jabatan_terakhir: string | undefined;
  nama_perusahaan: string | undefined;
  bidang_usaha: string | undefined;
  skala_perusahaan: string | undefined;
  tahun_berdiri_perusahaan: number | null | undefined;
  alamat_perusahaan: string | undefined;
  jumlah_karyawan: number | null | undefined;
  kondisi_pandemi: string | undefined;
  no_kontak_hr: number | null | undefined;
  tipe_pekerjaan_pasangan: string | undefined;
  status_pekerjaan_pasangan: string | undefined;
  lama_bekerja_bulan_pasangan: number | undefined;
  lama_bekerja_tahun_pasangan: number | null | undefined;
  jabatan_terakhir_pasangan: string | undefined;
  nama_perusahaan_pasangan: string | undefined;
  bidang_usaha_pasangan: string | undefined;
  skala_perusahaan_pasangan: string | undefined;
  tahun_berdiri_perusahaan_pasangan: number | null | undefined;
  alamat_perusahaan_pasangan: string | undefined;
  jumlah_karyawan_perusahaan_pasangan: number | null | undefined;
  kondisi_pandemi_perusahaan_pasangan: string | undefined;
  no_kontak_hr_pasangan: number | null | undefined;
  take_home_pay: number | null | undefined;
  estimasi_angsuran: number | null | undefined;
  validasi_rekening: string | undefined;
  keterangan: string | undefined;
  tanggal_wawancara: string | undefined;
  no_wawancara: string | undefined;
  legalitas_usaha: any;
  jenis_usaha: string | undefined;
  lama_usaha: number | null | undefined;
  kepemilikan_usaha: string | undefined;
  app_no_de: string | undefined;
  bulan_berdiri_perusahaan: number | null | undefined;
  bulan_berdiri_perusahaan_pasangan: number | null | undefined;
  cabang: string | undefined;
  created_by: string | undefined;
  created_date: string | undefined;
  curef: string | undefined;
  id: number | null | undefined;
  jenis_produk: string | undefined;
  kategori_pekerjaan: string | undefined;
  laba_periode_1: string | number | null | undefined;
  laba_periode_2: string | number | null | undefined;
  laba_periode_3: string | number | null | undefined;
  laba_periode_4: string | number | null | undefined;
  nama_ao: string | undefined;
  rata_rata_laba: string | number | null | undefined;
  tanggal_appraisal: string | undefined;
}
