export class getCallReportModel {
  alamat_tinggal: string | undefined | number | null;
  tanggal_lahir: string | undefined | number | null;
  status_kawin: string | undefined | number | null;
  pendidikan: string | undefined | number | null;
  kendaraan: string | undefined | number | null;
  status_agunan: string | undefined | number | null;
  catatan_status_agunan: string | undefined | number | null;
  dokumen_agunan: string | undefined | number | null;
  catatan_dokumen_agunan: string | undefined | number | null;
  posisi_dokumen: string | undefined | number | null;
  catatan_posisi_dokumen: string | undefined | number | null;
  tipe_pekerjaan: string | undefined | number | null;
  status_pekerjaan: string | undefined | number | null;
  lama_bekerja_tahun: string | undefined | number | null;
  lama_bekerja_bulan: string | undefined | number | null;
  jabatan_terakhir: string | undefined | number | null;
  nama_perusahaan: string | undefined | number | null;
  bidang_usaha: string | undefined | number | null;
  skala_perusahaan: string | undefined | number | null;
  tahun_berdiri_perusahaan: string | undefined | number | null;
  alamat_perusahaan: string | undefined | number | null;
  jumlah_karyawan: string | undefined | number | null;
  kondisi_pandemi: string | undefined | number | null;
  no_kontak_hr: string | undefined | number | null;
  tipe_pekerjaan_pasangan: string | undefined | number | null;
  status_pekerjaan_pasangan: string | undefined | number | null;
  lama_bekerja_bulan_pasangan: number | undefined;
  lama_bekerja_tahun_pasangan: string | undefined | number | null;
  jabatan_terakhir_pasangan: string | undefined | number | null;
  nama_perusahaan_pasangan: string | undefined | number | null;
  bidang_usaha_pasangan: string | undefined | number | null;
  skala_perusahaan_pasangan: string | undefined | number | null;
  tahun_berdiri_perusahaan_pasangan: string | undefined | number | null;
  alamat_perusahaan_pasangan: string | undefined | number | null;
  jumlah_karyawan_perusahaan_pasangan: string | undefined | number | null;
  kondisi_pandemi_perusahaan_pasangan: string | undefined | number | null;
  no_kontak_hr_pasangan: string | undefined | number | null;
  take_home_pay: string | undefined | number | null;
  estimasi_angsuran: string | undefined | number | null;
  validasi_rekening: string | undefined | number | null;
  keterangan: string | undefined | number | null;
  tanggal_wawancara: string | undefined | number | null;
  no_wawancara: string | undefined | number | null;
  legalitas_usaha: any;
  jenis_usaha: string | undefined | number | null;
  lama_usaha: string | undefined | number | null;
  kepemilikan_usaha: string | undefined | number | null;
  app_no_de: string | undefined | number | null;
  bulan_berdiri_perusahaan: string | undefined | number | null;
  bulan_berdiri_perusahaan_pasangan: string | undefined | number | null;
  cabang: string | undefined | number | null;
  created_by: string | undefined | number | null;
  created_date: string | undefined | number | null;
  curef: string | undefined | number | null;
  id: string | undefined | number | null;
  jenis_produk: string | undefined | number | null;
  kategori_pekerjaan: string | undefined | number | null;
  laba_periode_1: string | string | undefined | number | null;
  laba_periode_2: string | string | undefined | number | null;
  laba_periode_3: string | string | undefined | number | null;
  laba_periode_4: string | string | undefined | number | null;
  nama_ao: string | undefined | number | null;
  rata_rata_laba: string | string | undefined | number | null;
  tanggal_appraisal: string | undefined | number | null;
}
