export class listAgunan {
  id_collateral_detail?: number;
  id_collateral?: number;
  app_no_de?: string;
  curef?: string;
  tipe_agunan: string | number | undefined | null;
  tipe_properti?: string;
  status_agunan?: string;
  developer?: string;
  nama_perumahan?: string;
  status_jaminan_sebelumnya?: string;
  hubungan_pemegang_hak?: string;
  tahun_dibuat?: number;
  status_sertifikat: any;
  no_sertifikat?: string;
  nama_pemegang_hak?: string;
  no_handphone_cp?: number;
  no_id_pemegang_hak_sertifikat?: number;
  tanggal_terbit?: string;
  tanggal_expired?: string;
  alamat_agunan?: string;
  provinsi_agunan?: string;
  kabkota_agunan?: string;
  kecamatan_agunan?: string;
  kelurahan_agunan?: string;
  kode_pos_agunan: string | number | null | undefined;
  luas_bangunan?: number;
  luas_tanah?: number;
  harga_objek: string | number | null | undefined;
  alamat_sesuai_sertifikat?: string;
  provinsi_sesuai_sertifikat?: string;
  kabkota_sesuai_sertifikat?: string;
  kelurahan_sesuai_sertifikat?: string;
  kecamatan_sesuai_sertifikat?: string;
  kode_pos_sesuai_sertifikat: string | number | null | undefined;
  tipe_kendaraan?: string;
  merk?: string;
  model?: string;
  seri?: string;
  nomor_bpkb?: string;
  no_plat?: string;
  warna?: string;
  no_mesin?: string;
  no_rangka?: string;
  nama_bpkb?: string;
  jenis_objek?: number;
  status_developer?: string;
  rt?: number;
  rw?: number;
  rt_sertifikat?: number;
  rw_sertifikat?: number;
  jenis_objek_deskripsi?: string;
  status_active?: number;
  id_rumah?: string;
  nomor_rumah?: string;
  blok_rumah?: string;
  usia_bangunan?: string;
  negara_produsen?: string;
  berwawasan_lingkungan?: string;
  nilai_agunan: string | number | null | undefined;
  nilai_indikasi: string | number | null | undefined;
  nilai_likuidasi: string | number | null | undefined;
  nilai_pasar: string | number | null | undefined;
  no_faktur: string | number | null | undefined;
  no_spk: string | number | null | undefined;
  no_imb: string | number | null | undefined;
  tanggal_imb: string | number | null | undefined;
  harga_transaksi: string | number | null | undefined;
  nilai_pks: string | number | null | undefined;
  harga_objek_sertifikat: string | number | null | undefined;
  luas_bangunan_sertifikat: string | number | null | undefined;
  luas_tanah_sertifikat: string | number | null | undefined;
  agunan_tunai: string | number | null | undefined;
  no_rekening_agunan: string | number | null | undefined;
  status_agunan_tunai: string | number | null | undefined;
}
