export class listCreatemodel {
  akses_rumah?: any;
  active?: any;
  produk?: any;
  joint_income?: any;
  parameter?: any;
  data_value?: any;
  min_value?: any;
  max_value?: any;
  score?: any;
  jenis_developer?: any;
  kantor_cabang?: any;
  nama_developer?: any;
  fasilitas_listrik?: any;
  deskripsi?: any;
  jabatan_deskripsi?: any;
  jenis_objek_code?: any;
  jenis_objek_deskripsi?: any;
  kode_fasilitas?: any;
  fasilitas?: any;
  kode_akad: string | number | null | undefined;
  produk_deskripsi: any;
  kode_program: any;
  expired_date: any;
  min_plafond: any;
  max_plafond: any;
  program: any;
  dp_min: any;
  max_tenor: any;
  skema_deskripsi: any;
}
